"""Set True nullable

Revision ID: 7aa57ac7d918
Revises: f8919dd44507
Create Date: 2025-10-14 12:19:53.011251

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7aa57ac7d918'
down_revision: Union[str, Sequence[str], None] = 'f8919dd44507'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assets', 'asset_type',
                    existing_type=sa.VARCHAR(length=255),
                    nullable=True)
    op.alter_column('assets', 'asset_name',
                    existing_type=sa.VARCHAR(length=255),
                    nullable=True)
    op.alter_column('assets', 'asset_size',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('assets', 'asset_project_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('chunks', 'chunk_text',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.alter_column('chunks', 'chunk_metadata',
                    existing_type=postgresql.JSONB(astext_type=sa.Text()),
                    nullable=True)
    op.alter_column('chunks', 'chunk_project_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('chunks', 'chunk_asset_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chunks', 'chunk_asset_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.alter_column('chunks', 'chunk_project_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.alter_column('chunks', 'chunk_metadata',
                    existing_type=postgresql.JSONB(astext_type=sa.Text()),
                    nullable=False)
    op.alter_column('chunks', 'chunk_text',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.alter_column('assets', 'asset_project_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.alter_column('assets', 'asset_size',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.alter_column('assets', 'asset_name',
                    existing_type=sa.VARCHAR(length=255),
                    nullable=False)
    op.alter_column('assets', 'asset_type',
                    existing_type=sa.VARCHAR(length=255),
                    nullable=False)
    # ### end Alembic commands ###
