from enum import Enum

class ResponseSignal(Enum):
    FILE_UPLOADED_SUCCESSFULLY = "FILE_UPLOADED_SUCCESSFULLY"
    FILE_UPLOADED_FAILED = "FILE_UPLOADED_FAILED"
    FILE_TYPE_NOT_ALLOWED = "FILE_TYPE_NOT_ALLOWED"
    FILE_SIZE_EXCEEDED = "FILE_SIZE_EXCEEDED"
    FILE_VALIDATED_SUCCESSFULLY = "FILE_VALIDATED_SUCCESSFULLY"
